# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
joint_limits:
  # Default values for all joints
  default_velocity_scaling_factor: 1.0
  default_acceleration_scaling_factor: 1.0

  # Joint specific limits
  base_link__link_01:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_01__link_02:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_02__link_03:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_03__link_04:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_04__link_05:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_05__link_06:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_hand_cyl__first_fin:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0

  link_hand_cyl__second_fin:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -100.0
    max_position: 100.0
