planning_pipeline:
  planning_plugin: chomp_interface/CHOMPPlanner
  request_adapters: >
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints

planning_plugin: chomp_interface/CHOMPPlanner
planning_attempts: 10
planning_time: 5.0
max_velocity_scaling_factor: 1.0
max_acceleration_scaling_factor: 1.0

# Disable collision checking
collision_detection:
  type: moveit_core/CollisionDetector
  collision_detection: false

# Disable collision checking in planning scene
planning_scene_monitor:
  publish_robot_description: true
  publish_geometry_updates: true
  publish_state_updates: true
  publish_transforms_updates: true
  publish_planning_scene: true
  collision_detection: false

# Disable collision checking in trajectory execution
trajectory_execution:
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  allowed_goal_tolerance: 0.01
  collision_detection: false
