ruka_gz:
  ros__parameters:
    control_dt: 0.5 # 2 Hz
    use_sim_time: true
    joint_controller_name: 'ruka_arm_controller'
    joint_control_topic: 'joint_group_position_controller/commands'
    # end_effector_target_topic: 'end_effector_target_pose'
    # end_effector_pose_topic: 'end_effector_pose'
    model_file: 'config/gz/ruka_gz.urdf.xacro'
    base_frame: 'base_link__link_01'
    # end_effector_frame: 'end_effector_frame'
    # finger_joint_tag: 'finger' # tag for the joints to exclude from the IK optimization
    arm_joint_tag: 'ruka_arm_controller'
    initial_joint_angles: [0., 0., 0., 0., 0., 0.]
    joint_remapping: # necessary because ros messes up the joint states ordering
      base_link__link_01:       1
      link_01__link_02:         2
      link_02__link_03:         3
      link_03__link_04:         4
      link_04__link_05:         5
      link_05__link_06:         6
      
